CREATE TABLE Users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(255) ,
    email VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    role INT NOT NULL,
    profile_picture_url VARCHAR(500),
    refresh_token VARCHAR(500),
    refresh_token_expiry TIMESTAMP
);

CREATE INDEX idx_refresh_token ON Users(refresh_token);